// File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

/**
 * ADH6 API
 *
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AbstractMember { 
    /**
     * The unique identifier of this member
     */
    readonly id?: number;
    /**
     * The username of this member
     */
    username?: string;
    /**
     * The first name of this member
     */
    firstName?: string;
    /**
     * The last name of this member
     */
    lastName?: string;
    /**
     * The email address of this member
     */
    email?: string;
    /**
     * The optional comment for this member
     */
    comment?: string | null;
    /**
     * The date-time at which the subscription of this member expires
     */
    departureDate?: string;
    /**
     * The mailing lists the member is subscribed to (bit field)
     * @deprecated
     */
    mailinglist?: number;
    /**
     * The public ipv4 address assigned to this member
     */
    ip?: string | null;
    /**
     * The private ipv4 network assigned to this member
     */
    subnet?: string | null;
    /**
     * The current status of this membership request:  * `INITIAL` - Just created  * `PENDING_RULES` - Waiting for the member to sign the rules  * `PENDING_PAYMENT_INITIAL` - Initiating the payment flow  * `PENDING_PAYMENT` - During the payment flow  * `PENDING_PAYMENT_VALIDATION` - After the payment flow, waiting for confirmation  * `COMPLETE` - The membership request is completed  * `CANCELLED` - The membership has been cancelled  * `ABORTED` - The membership request flow was aborted Do note that some of the steps may be skipped depending on the payment method, whether or not this is the member\'s first membership request etc. 
     */
    membership?: AbstractMember.MembershipEnum | null;
    /**
     * Whether this account is permanent (never expires, always considered active)
     */
    permanent?: boolean;
    /**
     * Whether this account is wifi-only (no wired devices, no room assignment, cannot update subscription)
     */
    wifiOnly?: boolean;
}
export namespace AbstractMember {
    export type MembershipEnum = 'INITIAL' | 'PENDING_RULES' | 'PENDING_PAYMENT_INITIAL' | 'PENDING_PAYMENT' | 'PENDING_PAYMENT_VALIDATION' | 'COMPLETE' | 'CANCELLED' | 'ABORTED';
    export const MembershipEnum = {
        Initial: 'INITIAL' as MembershipEnum,
        PendingRules: 'PENDING_RULES' as MembershipEnum,
        PendingPaymentInitial: 'PENDING_PAYMENT_INITIAL' as MembershipEnum,
        PendingPayment: 'PENDING_PAYMENT' as MembershipEnum,
        PendingPaymentValidation: 'PENDING_PAYMENT_VALIDATION' as MembershipEnum,
        Complete: 'COMPLETE' as MembershipEnum,
        Cancelled: 'CANCELLED' as MembershipEnum,
        Aborted: 'ABORTED' as MembershipEnum
    };
}


