// File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

/**
 * ADH6 API
 *
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeviceFilter { 
    /**
     * The connection type of this device
     */
    connectionType?: DeviceFilter.ConnectionTypeEnum;
    /**
     * The id of the owner of this device
     */
    member?: number;
    terms?: string;
}
export namespace DeviceFilter {
    export type ConnectionTypeEnum = 'wired' | 'wireless';
    export const ConnectionTypeEnum = {
        Wired: 'wired' as ConnectionTypeEnum,
        Wireless: 'wireless' as ConnectionTypeEnum
    };
}


