// File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

/**
 * ADH6 API
 *
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MemberBody { 
    username?: string;
    firstName?: string;
    lastName?: string;
    mail?: string;
    /**
     * Whether this account is permanent (never expires, always considered active)
     */
    permanent?: boolean;
    /**
     * Whether this account is wifi-only (no wired devices, no room, cannot update subscription)
     */
    wifiOnly?: boolean;
}

