// File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

/**
 * ADH6 API
 *
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MiniRouterLoan { 
    /**
     * The unique identifier of this loan
     */
    readonly id?: number;
    /**
     * The loaned mini-router
     */
    readonly miniRouter?: number;
    /**
     * The factory MAC address of the loaned mini-router
     */
    readonly miniRouterHardwareMac?: string;
    /**
     * The member the mini-router is loaned to
     */
    member: number;
    /**
     * The first and last name of the member
     */
    readonly memberName?: string | null;
    /**
     * The start date of the loan
     */
    startedAt: string;
    /**
     * The date the mini-router must be returned
     */
    dueDate?: string | null;
    /**
     * The date the mini-router was returned, null while the loan is in progress
     */
    returnedAt?: string | null;
    /**
     * The deposit amount
     */
    depositAmount: number;
    /**
     * The payment method of the deposit
     */
    paymentMethod?: number | null;
    /**
     * The status of the deposit, always held when the loan is created
     */
    depositStatus?: MiniRouterLoan.DepositStatusEnum;
    /**
     * The member who created the loan and collected the deposit
     */
    readonly author?: number;
    /**
     * The first and last name of the author
     */
    readonly authorName?: string | null;
    /**
     * Whether the loan is in progress and past its due date
     */
    readonly overdue?: boolean;
}
export namespace MiniRouterLoan {
    export type DepositStatusEnum = 'held' | 'refunded' | 'kept';
    export const DepositStatusEnum = {
        Held: 'held' as DepositStatusEnum,
        Refunded: 'refunded' as DepositStatusEnum,
        Kept: 'kept' as DepositStatusEnum
    };
}


