// File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

/**
 * ADH6 API
 *
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Port { 
    /**
     * The unique identifier of this port
     */
    readonly id?: number;
    /**
     * The friendly (Cisco) number of this port
     */
    portNumber: string | null;
    /**
     * The oid of this port for SNMP access
     */
    oid: string;
    /**
     * The room this port is in
     */
    room: number | null;
    /**
     * The switch this port is a member of
     */
    switchObj: number;
}

