// File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

/**
 * ADH6 API
 *
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PortRoomAssignment { 
    /**
     * The target room\'s database identifier, or null to remove the assignment
     */
    room: number | null;
    /**
     * The current room\'s database identifier, or null for an unassigned port
     */
    expectedRoom: number | null;
}

