// File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

/**
 * ADH6 API
 *
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface RolePostRequest { 
    roles?: Array<Role>;
    /**
     * Login of the user that need the role
     */
    identifier?: string;
    auth?: RolePostRequest.AuthEnum;
}
export namespace RolePostRequest {
    export type AuthEnum = 'oidc' | 'user';
    export const AuthEnum = {
        Oidc: 'oidc' as AuthEnum,
        User: 'user' as AuthEnum
    };
}


