openapi: "3.0.3"
info:
  title: ADH6 API
  description: >
    This is the specification for **MiNET**'s ADH6 plaform. Its aim is to manage our users, devices and treasury.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
  contact:
    name: MiNET
    email: equipe@minet.net
    url: https://minet.net
servers:
  - url: https://adh6.minet.net/api/
    description: ADH6 production server
  - url: https://adh6-dev.minet.net/api/
    description: ADH6 staging server
paths:
  /health:
    get:
      summary: Retrieve the health of the API server
      description: >
        This endpoint allows for better monitoring of the state of the API.
        **TODO**: Improve the amount of information returned
      operationId: health
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - misc
  /profile:
    get:
      summary: Introspection endpoint
      description: >
        This endpoint returns information about the currently logged-in user.
      operationId: profile
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
      tags:
      - misc
  /account/:
    get:
      summary: Filter accounts
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - account
    post:
      summary: Create an account
      security: 
        - OAuth2:
          - treasurer:write
        - ApiKeyTreasuryAuth: []
      tags:
      - account
  /account/{id}:
    get:
      summary: Retrieve an account
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - account
    put:
      summary: Udate an account
      security: 
        - OAuth2:
          - treasurer:write
        - ApiKeyTreasuryAuth: []
      tags:
      - account
  /account_type/:
    get:
      summary: Filter account types
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - account
  /account_type/{id}:
    get:
      summary: Retrieve an account type
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - account
  /device/:
    get:
      summary: Return the list of the device ids
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - device
    post:
      summary: Create a device
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - device
  /device/{id}:
    delete:
      summary: Delete a device
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - device
    get:
      summary: Retrieve a device
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - device
  /device/{id}/vendor/:
    get:
      summary: Retrieve the vendor of a device based on its MAC
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - device
  /device/{id}/mab/:
    get:
      summary: Retreive the MAB of the device
      security: 
        - OAuth2:
          - admin:read
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth: []
      tags:
      - device
    post:
      summary: Update the MAB of the device
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - device
  /device/{id}/member/:
    get:
      summary: Get user of the device
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - device
  /member/:
    get:
      summary: Filter members
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - member
    post:
      summary: Create a member
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - member
  /member/{id}:
    delete:
      summary: Delete a member
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - member
    get:
      summary: Retrieve a member
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - member
    patch:
      summary: Partially update a member
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - member
  /member/{id}/logs/:
    get:
      summary: Retrieve the most recent logs of a member
      security: 
        - OAuth2:
          - admin:read
      tags:
      - member
  /member/{id}/statuses/:
    get:
      summary: Retrieves some common status updates concerning a member
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - member
  /member/{id}/password/:
    put:
      summary: Update the password of a member
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:write
      tags:
      - member
  /member/{id}/charter/{charter_id}:
    get:
      deprecated: true
      operationId: charter_get
      summary: Retrieves if the hosting charter has been signed
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - member
    put:
      deprecated: true
      operationId: charter_put
      summary: Update if the hosting/MiNET charter has been signed
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - member
  /member/{id}/comment/:
    put:
      summary: Update the comment of a member
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth:
          - admin:write
      tags:
      - member
    get:
      summary: Retrieves the comment of the user
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth:
          - admin:read
      tags:
      - member
  /member/{id}/subscription/:
    post:
      summary: Add a membership record for a member
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - membership
    patch:
      summary: Add a membership record for a member
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - membership
  /member/{id}/subscription/validate:
    post:
      operationId: subscription_validate
      summary: Validate a pending transaction
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - membership
  /charter/{charter_id}/member/:
    get:
      summary: List of the members that have signed the charter
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - charter
  /charter/{charter_id}/member/{id}:
    post:
      summary: Sign the specific charter
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - charter
    get:
      summary: Retreive the signature date of the specific charter
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - charter
  /mailinglist/member/{id}:
    get:
      summary: Retreive mailinglist memberships of the specific member
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - mailinglist
    put:
      summary: Update the mailing list membership of the member
      security:
        - OAuth2:
          - user
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - mailinglist
  /mailinglist/:
    get:
      summary: Retreive the members of a specific mailinglist memberships
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - mailinglist
  /payment_method/:
    get:
      summary: Filter payment methods
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - transaction
  /payment_method/{id}:
    get:
      summary: Retrieve a payment method
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - transaction
  /port/:
    get:
      summary: Filter ports
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - port
    post:
      summary: Create a port
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - port
  /port/{id}:
    delete:
      summary: Delete a port
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - port
    get:
      summary: Retrieve a port
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - port
    put:
      summary: Update a port
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - port
  /port/{id}/mab/:
    get:
      operationId: mab_get
      summary: Retrieve whether MAB is enabled on this port
      security: 
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth: []
      tags:
      - port
    put:
      summary: Update the state of MAB on a port
      security: 
        - OAuth2:
          - network:write
        - ApiKeyNetworkAuth: []
      tags:
      - port
  /port/{id}/alias/:
    get:
      operationId: alias_get
      summary: Retrieve the alias on a port
      security: 
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth: []
      tags:
      - port
  /port/{id}/use/:
    get:
      operationId: use_get
      summary: Retrieve the current use of a port
      security: 
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth: []
      tags:
      - port
  /port/{id}/speed/:
    get:
      operationId: speed_get
      summary: Retrieve the speed on a port
      security: 
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth: []
      tags:
      - port
  /port/{id}/auth/:
    get:
      operationId: auth_get
      summary: Retrieve whether authentication is enabled on this port
      security: 
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth: []
      tags:
      - port
    put:
      summary: Update the state of authentication on a port
      security: 
        - OAuth2:
          - network:write
        - ApiKeyNetworkAuth: []
      tags:
      - port
  /port/{id}/state/:
    get:
      operationId: state_get
      summary: Retrieve the state of a port
      security: 
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth: []
      tags:
      - port
    put:
      summary: Update the state of a port
      security: 
        - OAuth2:
          - network:write
        - ApiKeyNetworkAuth: []
      tags:
      - port
  /port/{id}/vlan/:
    get:
      operationId: vlan_get
      summary: Retrieve the VLAN assigned to a port
      security: 
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth: []
      tags:
      - port
    put:
      summary: Update the VLAN assigned to a port
      security: 
        - OAuth2:
          - network:write
          - network:write:prod
        - OAuth2:
          - network:write
          - network:write:dev
        - OAuth2:
          - network:write
          - network:write:hosting
        - ApiKeyNetworkAuth: []
      tags:
      - port
  /product/:
    get:
      summary: Filter products
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - treasury
  /product/{id}:
    get:
      summary: Retrieve a product
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - treasury
  /product/buy:
    post:
      summary: Generate a new transaction for a product
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - treasury
  /room/:
    get:
      summary: Filter rooms
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - room
    post:
      summary: Create a room
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - room
  /room/{id}:
    delete:
      summary: Delete a room
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - room
    get:
      summary: Retrieve a room
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - room
    put:
      summary: Update a room
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - room
  /room/{id}/member/:
    get:
      summary: List the members in a room
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth: []
      tags:
      - room members
    post:
      summary: Add a member in a room
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - room members
    delete:
      summary: Remove a member from a room
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth: []
      tags:
      - room members
  /room/{id}/member/add/:
    patch:
      deprecated: true
      summary: Add a member in a room
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth:
          - admin:write
      tags:
      - room members
  /room/{id}/member/del/:
    patch:
      deprecated: true
      summary: Remove a member from a room
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth:
          - admin:write
      tags:
      - room members
  /room/member/{id}:
    get:
      summary: List the members in a room
      security: 
        - OAuth2:
          - user
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth:
          - admin:read
      tags:
      - room members
  /switch/:
    get:
      summary: Filter switches
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth:
          - admin:read
      tags:
      - switch
    post:
      summary: Create a switch
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth:
          - admin:write
      tags:
      - switch
  /switch/{id}:
    delete:
      summary: Delete a switch
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth:
          - admin:read
      tags:
      - switch
    get:
      summary: Retrieve a switch
      security: 
        - OAuth2:
          - admin:read
        - ApiKeyAdminAuth:
          - admin:read
      tags:
      - switch
    put:
      summary: Update a switch
      security: 
        - OAuth2:
          - admin:write
        - ApiKeyAdminAuth:
          - admin:write
      tags:
      - switch
  /vlan/:
    get:
      operationId: get_from_number
      summary: Filter vlans
      security: 
        - OAuth2:
          - network:read
        - ApiKeyNetworkAuth:
          - network:read
      tags:
      - vlan
  /transaction/:
    get:
      summary: Filter transactions
      security: 
        - OAuth2:
          - treasurer:read
        - ApiKeyTreasuryAuth:
          - treasurer:read
      tags:
      - transaction
    post:
      summary: Create a transaction
      security: 
        - OAuth2:
          - treasurer:write
        - ApiKeyTreasuryAuth:
          - treasurer:write
      tags:
      - transaction
  /transaction/{id}/upload/:
    post:
      summary: Upload an attachment to a transaction
      security: 
        - OAuth2:
          - treasurer:write
        - ApiKeyTreasuryAuth:
          - treasurer:write
      tags:
      - transaction
  /transaction/{id}/validate:
    get:
      operationId: validate
      summary: Validate a pending transaction
      security: 
        - OAuth2:
          - treasurer:read
        - ApiKeyTreasuryAuth:
          - treasurer:read
      tags:
      - transaction
  /transaction/{id}:
    get:
      summary: Retrieve a transaction
      security: 
        - OAuth2:
          - treasurer:read
        - ApiKeyTreasuryAuth:
          - treasurer:read
      tags:
      - transaction
    patch:
      summary: Partially update a transaction
      security: 
        - OAuth2:
          - treasurer:write
        - ApiKeyTreasuryAuth:
          - treasurer:write
      tags:
      - transaction
    delete:
      summary: Delete a transaction (MUST only be possible when pendingValidation is true)
      security: 
        - OAuth2:
          - treasurer:write
        - ApiKeyTreasuryAuth:
          - treasurer:write
      tags:
      - transaction
  /treasury/cashbox:
    get:
      operationId: get_cashbox
      summary: Retrieve the state of the cashbox
      security: 
        - OAuth2:
          - treasurer:read
        - ApiKeyTreasuryAuth:
          - treasurer:read
      tags:
      - treasury
  /treasury/bank:
    get:
      operationId: get_bank
      summary: Retrieve the expected state of MiNET's bank accounts
      security: 
        - OAuth2:
          - treasurer:read
        - ApiKeyTreasuryAuth:
          - treasurer:read
      tags:
      - treasury
  /role/:
    get:
      summary: Filter roles
      security: 
        - OAuth2:
          - admin:read
          - admin:prod
        - ApiKeyAdminAuth:
          - admin:read
      tags:
      - authentication
    post:
      summary: Create a temporary role for a user
      security: 
        - OAuth2:
          - admin:write
          - admin:prod
      tags:
      - authentication
  /role/{id}:
    delete:
      summary: Delete a Role
      security: 
        - OAuth2:
          - admin:write
          - admin:prod
        - ApiKeyAdminAuth:
          - admin:write
      tags:
      - authentication
  /api_keys/:
    get:
      summary: List api keys
      security: 
        - OAuth2:
          - admin:read
          - admin:prod
      tags:
      - authentication
    post:
      summary: Create an ApiKey
      security: 
        - OAuth2:
          - admin:write
          - admin:prod
      tags:
      - authentication
  /api_keys/{id}:
    delete:
      summary: Delete an Api Key
      security: 
        - OAuth2:
          - admin:write
          - admin:prod
      tags:
      - authentication
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://cas.minet.net/oidc/authorize
          scopes:
            profile: The user's basic information, including groups they are a part of
    ApiKeyAdminAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      x-apikeyInfoFunc: adh6.authentication.apikey_admin_auth
    ApiKeyNetworkAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      x-apikeyInfoFunc: adh6.authentication.apikey_network_auth
    ApiKeyTreasuryAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      x-apikeyInfoFunc: adh6.authentication.apikey_treasury_auth
tags:
- description: Operations on members
  name: member
- description: Manage membership records
  name: membership
- description: Operations on the charters
  name: charter
- description: Operations on the mailinglists
  name: mailinglist
- description: Operations on devices
  name: device
- description: Operations on rooms
  name: room
- description: Operation on the members in a room
  name: room members
- description: Operations on VLANs
  name: vlan
- description: Operations on switches
  name: switch
- description: Operations on ports
  name: port
- description: Operations on accounts
  name: account
- description: Operations on transactions
  name: transaction
- description: Operations on the treasury
  name: treasury
- description: Miscellaneous endpoints
  name: misc
