# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

# coding: utf-8

"""
    ADH6 API

    This is the specification for **MiNET**'s ADH6 plaform. Its aim is to manage our users, devices and treasury. 

    The version of the OpenAPI document: 2.0.0
    Contact: equipe@minet.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AbstractPaymentMethod(BaseModel):
    """
    AbstractPaymentMethod
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The unique identifier of this payment method")
    static_fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The static fee for this payment method in euros", alias="staticFee")
    dynamic_fee: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="The dynamic fee for this payment method as a percentage", alias="dynamicFee")
    name: Optional[StrictStr] = Field(default=None, description="The friendly name of this payment method")
    __properties: ClassVar[List[str]] = ["id", "staticFee", "dynamicFee", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AbstractPaymentMethod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if static_fee (nullable) is None
        # and model_fields_set contains the field
        if self.static_fee is None and "static_fee" in self.model_fields_set:
            _dict['staticFee'] = None

        # set to None if dynamic_fee (nullable) is None
        # and model_fields_set contains the field
        if self.dynamic_fee is None and "dynamic_fee" in self.model_fields_set:
            _dict['dynamicFee'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AbstractPaymentMethod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "staticFee": obj.get("staticFee"),
            "dynamicFee": obj.get("dynamicFee"),
            "name": obj.get("name")
        })
        return _obj


