# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.
# type: ignore

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from adh6.entity.base_model import Model
from adh6 import util


class Bank(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expected_cav=None):  # noqa: E501
        """Bank - a model defined in OpenAPI

        :param expected_cav: The expected_cav of this Bank.  # noqa: E501
        :type expected_cav: float
        """
        self.openapi_types = {
            'expected_cav': float
        }

        self.attribute_map = {
            'expected_cav': 'expectedCav'
        }

        self._expected_cav = expected_cav

    @classmethod
    def from_dict(cls, dikt) -> 'Bank':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bank of this Bank.  # noqa: E501
        :rtype: Bank
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expected_cav(self) -> float:
        """Gets the expected_cav of this Bank.

        the expected balance of MiNET's CAV accunt  # noqa: E501

        :return: The expected_cav of this Bank.
        :rtype: float
        """
        return self._expected_cav

    @expected_cav.setter
    def expected_cav(self, expected_cav: float):
        """Sets the expected_cav of this Bank.

        the expected balance of MiNET's CAV accunt  # noqa: E501

        :param expected_cav: The expected_cav of this Bank.
        :type expected_cav: float
        """

        self._expected_cav = expected_cav
