# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.
# type: ignore

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from adh6.entity.base_model import Model
from adh6 import util


class Cashbox(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, fond=None, coffre=None):  # noqa: E501
        """Cashbox - a model defined in OpenAPI

        :param fond: The fond of this Cashbox.  # noqa: E501
        :type fond: float
        :param coffre: The coffre of this Cashbox.  # noqa: E501
        :type coffre: float
        """
        self.openapi_types = {
            'fond': float,
            'coffre': float
        }

        self.attribute_map = {
            'fond': 'fond',
            'coffre': 'coffre'
        }

        self._fond = fond
        self._coffre = coffre

    @classmethod
    def from_dict(cls, dikt) -> 'Cashbox':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cashbox of this Cashbox.  # noqa: E501
        :rtype: Cashbox
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fond(self) -> float:
        """Gets the fond of this Cashbox.

        balance in the cashbox  # noqa: E501

        :return: The fond of this Cashbox.
        :rtype: float
        """
        return self._fond

    @fond.setter
    def fond(self, fond: float):
        """Sets the fond of this Cashbox.

        balance in the cashbox  # noqa: E501

        :param fond: The fond of this Cashbox.
        :type fond: float
        """

        self._fond = fond

    @property
    def coffre(self) -> float:
        """Gets the coffre of this Cashbox.

        balance in the coffre  # noqa: E501

        :return: The coffre of this Cashbox.
        :rtype: float
        """
        return self._coffre

    @coffre.setter
    def coffre(self, coffre: float):
        """Sets the coffre of this Cashbox.

        balance in the coffre  # noqa: E501

        :param coffre: The coffre of this Cashbox.
        :type coffre: float
        """

        self._coffre = coffre
