# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.
# type: ignore

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from adh6.entity.base_model import Model
from adh6 import util


class MailinglistMemberIdPutRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None):  # noqa: E501
        """MailinglistMemberIdPutRequest - a model defined in OpenAPI

        :param value: The value of this MailinglistMemberIdPutRequest.  # noqa: E501
        :type value: int
        """
        self.openapi_types = {
            'value': int
        }

        self.attribute_map = {
            'value': 'value'
        }

        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'MailinglistMemberIdPutRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _mailinglist_member__id__put_request of this MailinglistMemberIdPutRequest.  # noqa: E501
        :rtype: MailinglistMemberIdPutRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this MailinglistMemberIdPutRequest.

        the value of the subscription  # noqa: E501

        :return: The value of this MailinglistMemberIdPutRequest.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this MailinglistMemberIdPutRequest.

        the value of the subscription  # noqa: E501

        :param value: The value of this MailinglistMemberIdPutRequest.
        :type value: int
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501
        if value is not None and value > 255:  # noqa: E501
            raise ValueError("Invalid value for `value`, must be a value less than or equal to `255`")  # noqa: E501
        if value is not None and value < 0:  # noqa: E501
            raise ValueError("Invalid value for `value`, must be a value greater than or equal to `0`")  # noqa: E501

        self._value = value
