# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

# coding: utf-8

"""
    ADH6 API

    This is the specification for **MiNET**'s ADH6 plaform. Its aim is to manage our users, devices and treasury. 

    The version of the OpenAPI document: 2.0.0
    Contact: equipe@minet.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MemberStatus(BaseModel):
    """
    MemberStatus
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The status id :  * `LOGIN_INCORRECT_WRONG_USER` - Some MAC address tried logging in with the wrong username  * `LOGIN_INCORRECT_WRONG_MAC` - The user tried logging in with a MAC address not registered or belonging to another user  * `LOGIN_INCORRECT_WRONG_PASSWORD` - The user tried logging in with the correct MAC address/username combo but an incorrect password  * `LOGIN_INCORRECT_SSL_ERROR` - The user has enabled certificate verification OR another SSL error occurred (invalid time sync...)  * `LOGIN_DEVICE_ERROR` - A device could not be authentified, the other statuses might provide more details ")
    comment: Optional[StrictStr] = Field(default=None, description="Additionnal data regarding this status")
    last_timestamp: Optional[datetime] = Field(default=None, description="When this status was last reported", alias="lastTimestamp")
    __properties: ClassVar[List[str]] = ["status", "comment", "lastTimestamp"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['LOGIN_INCORRECT_WRONG_USER', 'LOGIN_INCORRECT_WRONG_MAC', 'LOGIN_INCORRECT_WRONG_PASSWORD', 'LOGIN_INCORRECT_SSL_ERROR', 'LOGIN_DEVICE_ERROR']):
            raise ValueError("must be one of enum values ('LOGIN_INCORRECT_WRONG_USER', 'LOGIN_INCORRECT_WRONG_MAC', 'LOGIN_INCORRECT_WRONG_PASSWORD', 'LOGIN_INCORRECT_SSL_ERROR', 'LOGIN_DEVICE_ERROR')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return self.model_dump_json(by_alias=True, exclude_none=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MemberStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MemberStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "comment": obj.get("comment"),
            "lastTimestamp": obj.get("lastTimestamp")
        })
        return _obj


