# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.
# type: ignore

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from adh6.entity.base_model import Model
from adh6 import util


class PaymentMethod(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, static_fee=None, dynamic_fee=None, name=None):  # noqa: E501
        """PaymentMethod - a model defined in OpenAPI

        :param id: The id of this PaymentMethod.  # noqa: E501
        :type id: int
        :param static_fee: The static_fee of this PaymentMethod.  # noqa: E501
        :type static_fee: float
        :param dynamic_fee: The dynamic_fee of this PaymentMethod.  # noqa: E501
        :type dynamic_fee: float
        :param name: The name of this PaymentMethod.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'id': int,
            'static_fee': float,
            'dynamic_fee': float,
            'name': str
        }

        self.attribute_map = {
            'id': 'id',
            'static_fee': 'staticFee',
            'dynamic_fee': 'dynamicFee',
            'name': 'name'
        }

        self._id = id
        self._static_fee = static_fee
        self._dynamic_fee = dynamic_fee
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'PaymentMethod':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaymentMethod of this PaymentMethod.  # noqa: E501
        :rtype: PaymentMethod
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this PaymentMethod.

        The unique identifier of this payment method  # noqa: E501

        :return: The id of this PaymentMethod.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PaymentMethod.

        The unique identifier of this payment method  # noqa: E501

        :param id: The id of this PaymentMethod.
        :type id: int
        """

        self._id = id

    @property
    def static_fee(self) -> float:
        """Gets the static_fee of this PaymentMethod.

        The static fee for this payment method in euros  # noqa: E501

        :return: The static_fee of this PaymentMethod.
        :rtype: float
        """
        return self._static_fee

    @static_fee.setter
    def static_fee(self, static_fee: float):
        """Sets the static_fee of this PaymentMethod.

        The static fee for this payment method in euros  # noqa: E501

        :param static_fee: The static_fee of this PaymentMethod.
        :type static_fee: float
        """

        self._static_fee = static_fee

    @property
    def dynamic_fee(self) -> float:
        """Gets the dynamic_fee of this PaymentMethod.

        The dynamic fee for this payment method as a percentage  # noqa: E501

        :return: The dynamic_fee of this PaymentMethod.
        :rtype: float
        """
        return self._dynamic_fee

    @dynamic_fee.setter
    def dynamic_fee(self, dynamic_fee: float):
        """Sets the dynamic_fee of this PaymentMethod.

        The dynamic fee for this payment method as a percentage  # noqa: E501

        :param dynamic_fee: The dynamic_fee of this PaymentMethod.
        :type dynamic_fee: float
        """
        if dynamic_fee is not None and dynamic_fee > 1:  # noqa: E501
            raise ValueError("Invalid value for `dynamic_fee`, must be a value less than or equal to `1`")  # noqa: E501
        if dynamic_fee is not None and dynamic_fee < 0:  # noqa: E501
            raise ValueError("Invalid value for `dynamic_fee`, must be a value greater than or equal to `0`")  # noqa: E501

        self._dynamic_fee = dynamic_fee

    @property
    def name(self) -> str:
        """Gets the name of this PaymentMethod.

        The friendly name of this payment method  # noqa: E501

        :return: The name of this PaymentMethod.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PaymentMethod.

        The friendly name of this payment method  # noqa: E501

        :param name: The name of this PaymentMethod.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
