# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.
# type: ignore

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from adh6.entity.base_model import Model
from adh6 import util


class Port(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, port_number=None, oid=None, room=None, switch_obj=None):  # noqa: E501
        """Port - a model defined in OpenAPI

        :param id: The id of this Port.  # noqa: E501
        :type id: int
        :param port_number: The port_number of this Port.  # noqa: E501
        :type port_number: str
        :param oid: The oid of this Port.  # noqa: E501
        :type oid: str
        :param room: The room of this Port.  # noqa: E501
        :type room: int
        :param switch_obj: The switch_obj of this Port.  # noqa: E501
        :type switch_obj: int
        """
        self.openapi_types = {
            'id': int,
            'port_number': str,
            'oid': str,
            'room': int,
            'switch_obj': int
        }

        self.attribute_map = {
            'id': 'id',
            'port_number': 'portNumber',
            'oid': 'oid',
            'room': 'room',
            'switch_obj': 'switchObj'
        }

        self._id = id
        self._port_number = port_number
        self._oid = oid
        self._room = room
        self._switch_obj = switch_obj

    @classmethod
    def from_dict(cls, dikt) -> 'Port':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Port of this Port.  # noqa: E501
        :rtype: Port
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Port.

        The unique identifier of this port  # noqa: E501

        :return: The id of this Port.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Port.

        The unique identifier of this port  # noqa: E501

        :param id: The id of this Port.
        :type id: int
        """

        self._id = id

    @property
    def port_number(self) -> str:
        """Gets the port_number of this Port.

        The friendly (Cisco) number of this port  # noqa: E501

        :return: The port_number of this Port.
        :rtype: str
        """
        return self._port_number

    @port_number.setter
    def port_number(self, port_number: str):
        """Sets the port_number of this Port.

        The friendly (Cisco) number of this port  # noqa: E501

        :param port_number: The port_number of this Port.
        :type port_number: str
        """
        if port_number is None:
            raise ValueError("Invalid value for `port_number`, must not be `None`")  # noqa: E501

        self._port_number = port_number

    @property
    def oid(self) -> str:
        """Gets the oid of this Port.

        The oid of this port for SNMP access  # noqa: E501

        :return: The oid of this Port.
        :rtype: str
        """
        return self._oid

    @oid.setter
    def oid(self, oid: str):
        """Sets the oid of this Port.

        The oid of this port for SNMP access  # noqa: E501

        :param oid: The oid of this Port.
        :type oid: str
        """
        if oid is None:
            raise ValueError("Invalid value for `oid`, must not be `None`")  # noqa: E501

        self._oid = oid

    @property
    def room(self) -> int:
        """Gets the room of this Port.

        The room this port is in  # noqa: E501

        :return: The room of this Port.
        :rtype: int
        """
        return self._room

    @room.setter
    def room(self, room: int):
        """Sets the room of this Port.

        The room this port is in  # noqa: E501

        :param room: The room of this Port.
        :type room: int
        """
        if room is None:
            raise ValueError("Invalid value for `room`, must not be `None`")  # noqa: E501

        self._room = room

    @property
    def switch_obj(self) -> int:
        """Gets the switch_obj of this Port.

        The switch this port is a member of  # noqa: E501

        :return: The switch_obj of this Port.
        :rtype: int
        """
        return self._switch_obj

    @switch_obj.setter
    def switch_obj(self, switch_obj: int):
        """Sets the switch_obj of this Port.

        The switch this port is a member of  # noqa: E501

        :param switch_obj: The switch_obj of this Port.
        :type switch_obj: int
        """
        if switch_obj is None:
            raise ValueError("Invalid value for `switch_obj`, must not be `None`")  # noqa: E501

        self._switch_obj = switch_obj
