# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.
# type: ignore

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from adh6.entity.base_model import Model
from adh6.entity.role import Role
from adh6 import util

from adh6.entity.role import Role  # noqa: E501

class RoleMapping(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, role=None, authentication=None, identifier=None):  # noqa: E501
        """RoleMapping - a model defined in OpenAPI

        :param id: The id of this RoleMapping.  # noqa: E501
        :type id: int
        :param role: The role of this RoleMapping.  # noqa: E501
        :type role: Role
        :param authentication: The authentication of this RoleMapping.  # noqa: E501
        :type authentication: str
        :param identifier: The identifier of this RoleMapping.  # noqa: E501
        :type identifier: str
        """
        self.openapi_types = {
            'id': int,
            'role': Role,
            'authentication': str,
            'identifier': str
        }

        self.attribute_map = {
            'id': 'id',
            'role': 'role',
            'authentication': 'authentication',
            'identifier': 'identifier'
        }

        self._id = id
        self._role = role
        self._authentication = authentication
        self._identifier = identifier

    @classmethod
    def from_dict(cls, dikt) -> 'RoleMapping':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoleMapping of this RoleMapping.  # noqa: E501
        :rtype: RoleMapping
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this RoleMapping.


        :return: The id of this RoleMapping.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this RoleMapping.


        :param id: The id of this RoleMapping.
        :type id: int
        """

        self._id = id

    @property
    def role(self) -> Role:
        """Gets the role of this RoleMapping.


        :return: The role of this RoleMapping.
        :rtype: Role
        """
        return self._role

    @role.setter
    def role(self, role: Role):
        """Sets the role of this RoleMapping.


        :param role: The role of this RoleMapping.
        :type role: Role
        """

        self._role = role

    @property
    def authentication(self) -> str:
        """Gets the authentication of this RoleMapping.


        :return: The authentication of this RoleMapping.
        :rtype: str
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication: str):
        """Sets the authentication of this RoleMapping.


        :param authentication: The authentication of this RoleMapping.
        :type authentication: str
        """
        allowed_values = ["oidc", "api_key", "user"]  # noqa: E501
        if authentication not in allowed_values:
            raise ValueError(
                "Invalid value for `authentication` ({0}), must be one of {1}"
                .format(authentication, allowed_values)
            )

        self._authentication = authentication

    @property
    def identifier(self) -> str:
        """Gets the identifier of this RoleMapping.

        The login of the user link to the api key  # noqa: E501

        :return: The identifier of this RoleMapping.
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier: str):
        """Sets the identifier of this RoleMapping.

        The login of the user link to the api key  # noqa: E501

        :param identifier: The identifier of this RoleMapping.
        :type identifier: str
        """

        self._identifier = identifier
