# File generated using spec-to-code.sh, DO NOT EDIT MANUALLY.

# coding: utf-8

"""
    ADH6 API

    This is the specification for **MiNET**'s ADH6 plaform. Its aim is to manage our users, devices and treasury. 

    The version of the OpenAPI document: 2.0.0
    Contact: equipe@minet.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Role(str, Enum):
    """
    Role
    """

    """
    allowed enum values
    """
    USER = 'user'
    ADMIN_COLON_READ = 'admin:read'
    ADMIN_COLON_WRITE = 'admin:write'
    ADMIN_COLON_PROD = 'admin:prod'
    TREASURER_COLON_READ = 'treasurer:read'
    TREASURER_COLON_WRITE = 'treasurer:write'
    NETWORK_COLON_READ = 'network:read'
    NETWORK_COLON_WRITE = 'network:write'
    NETWORK_COLON_WRITE_COLON_PROD = 'network:write:prod'
    NETWORK_COLON_WRITE_COLON_DEV = 'network:write:dev'
    NETWORK_COLON_WRITE_COLON_HOSTING = 'network:write:hosting'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Role from a JSON string"""
        return cls(json.loads(json_str))


