stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_REGISTRY_BASE: $CI_REGISTRY_IMAGE
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: 1

.docker_login: &docker_login
  image: docker:latest
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - |
      if [ "$CI_COMMIT_BRANCH" = "master" ]; then
        TAG="stable"
      elif [ "$CI_COMMIT_BRANCH" = "dev" ]; then
        TAG="prep"
      else
        TAG="$CI_COMMIT_SHORT_SHA"
      fi

.branch_rules:
  rules: &branch_rules
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master")'
      when: always
    - when: never

.feature_rules:
  rules: &feature_rules
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "dev" && $CI_COMMIT_BRANCH != "master"'
      when: always
    - when: never

build_backend:
  <<: *docker_login
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master")'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "dev" && $CI_COMMIT_BRANCH != "master"'
      when: always
    - when: never
  script:
    - docker pull $IMAGE_REGISTRY_BASE/backend:$TAG || true
    - docker pull $IMAGE_REGISTRY_BASE/backend-test:$TAG || true
    - docker build
        --cache-from $IMAGE_REGISTRY_BASE/backend:$TAG
        --build-arg BUILDKIT_INLINE_CACHE=1
        --target prod
        --file backend/Dockerfile
        --tag $IMAGE_REGISTRY_BASE/backend:$TAG
        .
    - docker build
        --cache-from $IMAGE_REGISTRY_BASE/backend-test:$TAG
        --build-arg BUILDKIT_INLINE_CACHE=1
        --target test
        --file backend/Dockerfile
        --tag $IMAGE_REGISTRY_BASE/backend-test:$TAG
        .
    - docker push $IMAGE_REGISTRY_BASE/backend:$TAG
    - docker push $IMAGE_REGISTRY_BASE/backend-test:$TAG

build_frontend:
  <<: *docker_login
  stage: build
  rules: *branch_rules
  script:
    - docker pull $IMAGE_REGISTRY_BASE/frontend:$TAG || true
    - docker build
        --cache-from $IMAGE_REGISTRY_BASE/frontend:$TAG
        --build-arg BUILDKIT_INLINE_CACHE=1
        --target prod
        --file frontend/Dockerfile
        --tag $IMAGE_REGISTRY_BASE/frontend:$TAG
        .
    - docker push $IMAGE_REGISTRY_BASE/frontend:$TAG

build_reverse_proxy:
  <<: *docker_login
  stage: build
  rules: *branch_rules
  script:
    - docker pull $IMAGE_REGISTRY_BASE/reverse_proxy:$TAG || true
    - docker build
        --cache-from $IMAGE_REGISTRY_BASE/reverse_proxy:$TAG
        --build-arg BUILDKIT_INLINE_CACHE=1
        --file reverse_proxy/Dockerfile
        --tag $IMAGE_REGISTRY_BASE/reverse_proxy:$TAG
        .
    - docker push $IMAGE_REGISTRY_BASE/reverse_proxy:$TAG

test_backend:
  stage: test
  before_script: []
  script:
    - cd backend && uv run tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"'
      when: always
      variables:
        TAG: stable
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
      when: always
      variables:
        TAG: prep
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "dev" && $CI_COMMIT_BRANCH != "master"'
      when: always
      variables:
        TAG: $CI_COMMIT_SHORT_SHA
    - when: never
  image:
    name: $IMAGE_REGISTRY_BASE/backend-test:$TAG
  needs:
    - build_backend

deploy_prod:
  stage: deploy
  trigger:
    project: minet/configurations/push/swarm-prod
    branch: main
    strategy: depend
    inputs:
      folder_name: adh6.minet.net
      image_registry: $CI_REGISTRY_IMAGE
  needs:
    - build_backend
    - build_frontend
    - build_reverse_proxy
    - test_backend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never

deploy_dev:
  stage: deploy
  trigger:
    project: minet/configurations/push/swarm-prod
    branch: main
    strategy: depend
    inputs:
      folder_name: adh6-dev.minet.net
      image_registry: $CI_REGISTRY_IMAGE
  needs:
    - build_backend
    - build_frontend
    - build_reverse_proxy
    - test_backend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
      when: always
    - when: never
