name: adh6

services:
  frontend_angular:
    container_name: adh6_frontend
    build:
      context: .
      dockerfile: docker/frontend_angular/Dockerfile
      target: dev
    develop:
      watch:
        - action: sync
          path: frontend_angular/src
          target: /app/frontend_angular/src
        - action: rebuild
          path: frontend_angular/angular.json
        - action: rebuild
          path: openapi/spec.yaml

  api_server:
    container_name: adh6_backend
    init: true
    build:
      context: .
      dockerfile: docker/backend_connexion/Dockerfile
      target: dev
    depends_on:
      database:
        condition: service_healthy
    environment:
      ENVIRONMENT: "development"
      OAUTH2_BASE_PATH: "https://cas.minet.net/oidc/profile"
      DATABASE_HOST: ${DATABASE_HOST:-database}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-adh6}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-adh6pass}
      DATABASE_DB_NAME: ${DATABASE_DB_NAME:-adh6}
    develop:
      watch:
        - path: api_server/adh6
          target: /app/api_server/adh6
          action: sync
          ignore:
            - api_server/adh6/typing_utils.py
            - api_server/adh6/utils.py
            - api_server/adh6/entity

  reverse_proxy:
    container_name: adh6_reverse_proxy
    build:
      context: .
      dockerfile: docker/reverse_proxy/Dockerfile
    init: true
    links:
      - frontend_angular
      - api_server
    ports:
      - "443:443"
      - "80:80"
    environment:
      ADH6_URL: "adh6-local.minet.net"
      API_HOST: "api_server"
      API_PORT: "8080"
      FRONTEND_HOST: "frontend_angular"
      FRONTEND_PORT: "80"
    command: [ 'nginx-debug', '-g', 'daemon off;' ]

  database:
    read_only: true
    container_name: adh6_database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${DATABASE_DB_NAME:-adh6}
      MYSQL_USER: ${DATABASE_USERNAME:-adh6}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-adh6pass}
    ports:
      - 3306:3306
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/lib/mysql:rw
      - /tmp:rw
      - /run/mysqld/:rw
    healthcheck:
      test: "/usr/bin/mysql --user=${DATABASE_USERNAME:-adh6} --password=${DATABASE_PASSWORD:-adh6pass} --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
  # jaeger:
  #   image: jaegertracing/all-in-one:1.22
  #   environment:
  #     COLLECTOR_ZIPKIN_HOST_PORT: :9411
  #   ports:
  #     - 16686:16686
