services:
  backend:
    build:
      target: debug # Override du target pour utiliser le stage debug
    ports:
      - "5678:5678" # Port pour debugpy
    environment:
      DEBUG: "1"
      LOG_LEVEL: "DEBUG"
      PYTHONUNBUFFERED: "1"
