# coding=utf-8
import enum

CTX_SQL_SESSION = 'sql_session'
CTX_ADMIN = 'admin'
CTX_TESTING = 'testing'
CTX_REQUEST_ID = 'request_uuid'
CTX_REQUEST_URL = 'url'
CTX_ROLES = 'roles'

DEFAULT_LIMIT = 100
DEFAULT_OFFSET = 0
LOG_DEFAULT_LIMIT = 10

class MembershipStatus(enum.Enum):
    INITIAL = "INITIAL"
    PENDING_RULES = "PENDING_RULES"
    PENDING_PAYMENT_INITIAL = "PENDING_PAYMENT_INITIAL"
    PENDING_PAYMENT = "PENDING_PAYMENT"
    PENDING_PAYMENT_VALIDATION = "PENDING_PAYMENT_VALIDATION"
    COMPLETE = "COMPLETE"
    CANCELLED = "CANCELLED"
    ABORTED = "ABORTED"


class MembershipDuration(enum.IntEnum):
    NONE = 0
    ONE_MONTH = 1
    TWO_MONTH = 2
    THREE_MONTH = 3
    FOUR_MONTH = 4
    FIVE_MONTH = 5
    SIX_MONTH = 6
    ONE_YEAR = 12