/**
 * ADH6 API
 * This is the specification for **MiNET**'s ADH6 plaform. Its aim is to manage our users, devices and treasury. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AbstractPaymentMethod { 
    /**
     * The unique identifier of this payment method
     */
    readonly id?: number;
    /**
     * The static fee for this payment method in euros
     */
    staticFee?: number;
    /**
     * The dynamic fee for this payment method as a percentage
     */
    dynamicFee?: number;
    /**
     * The friendly name of this payment method
     */
    name?: string;
}