/**
 * ADH6 API
 * This is the specification for **MiNET**'s ADH6 plaform. Its aim is to manage our users, devices and treasury. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AbstractVlan { 
    __typename?: string;
    /**
     * The unique identifier of this vlan
     */
    readonly id?: number;
    /**
     * The number of this VLAN
     */
    number?: number;
    /**
     * The IPv4 network range for this VLAN
     */
    ipv4Network?: string;
    /**
     * The IPv6 network range for this VLAN
     */
    ipv6Network?: string;
}
