/**
 * ADH6 API
 * This is the specification for **MiNET**'s ADH6 plaform. Its aim is to manage our users, devices and treasury. 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: equipe@minet.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentMethod } from './paymentMethod';

export interface MembershipRequest { 
    __typename?: string;
    /**
     * The duration in days this membership is for
     */
    duration: number;
    /**
     * The payment method used to pay the membership fee
     */
    paymentMethod: PaymentMethod | number;
    /**
     * Whether or not this membership request is the member's first
     */
    firstTime: boolean;
}
