/**
 * Adherent
 * Adherent api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Member } from './member';
import { PaymentMethod } from './paymentMethod';

export interface Transaction { 
    readonly id?: number;
    name: string;
    src: Account;
    readonly dst: Account;
    readonly timestamp?: Date;
    paymentMethod: PaymentMethod;
    value: number;
    attachments?: string;
    author?: Member;
    pendingValidation?: boolean;
}