/**
 * Adherent
 * Adherent api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TransactionPatchRequest { 
    name?: string;
    value?: number;
    attachments?: string;
    src?: number;
    dst?: number;
    paymentMethod?: number;
    caisse?: TransactionPatchRequest.CaisseEnum;
}
export namespace TransactionPatchRequest {
    export type CaisseEnum = 'to' | 'from' | 'direct';
    export const CaisseEnum = {
        To: 'to' as CaisseEnum,
        From: 'from' as CaisseEnum,
        Direct: 'direct' as CaisseEnum
    };
}