"""empty message

Revision ID: d86cfea89f3e
Revises: e88207e7b76e
Create Date: 2022-08-01 00:44:01.858396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86cfea89f3e'
down_revision = 'e88207e7b76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms_members_association',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('room_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms_members_association')
    # ### end Alembic commands ###
