# coding: utf-8

"""
    ADH6 API

    This is the specification for **MiNET**'s ADH6 plaform. Its aim is to manage our users, devices and treasury.   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: equipe@minet.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from src.entity.decorator.entity_property import entity_property


class AbstractPaymentMethod(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'static_fee': 'float',
        'dynamic_fee': 'float',
        'name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'static_fee': 'staticFee',
        'dynamic_fee': 'dynamicFee',
        'name': 'name'
    }

    def __init__(self, id=None, static_fee=None, dynamic_fee=None, name=None):  # noqa: E501
        """AbstractPaymentMethod - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._static_fee = None
        self._dynamic_fee = None
        self._name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if static_fee is not None:
            self.static_fee = static_fee
        if dynamic_fee is not None:
            self.dynamic_fee = dynamic_fee
        if name is not None:
            self.name = name

    @entity_property
    def id(self):
        """Gets the id of this AbstractPaymentMethod.  # noqa: E501

        The unique identifier of this payment method  # noqa: E501

        :return: The id of this AbstractPaymentMethod.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AbstractPaymentMethod.

        The unique identifier of this payment method  # noqa: E501

        :param id: The id of this AbstractPaymentMethod.  # noqa: E501
        :type: int
        """

        self._id = id

    @entity_property
    def static_fee(self):
        """Gets the static_fee of this AbstractPaymentMethod.  # noqa: E501

        The static fee for this payment method in euros  # noqa: E501

        :return: The static_fee of this AbstractPaymentMethod.  # noqa: E501
        :rtype: float
        """
        return self._static_fee

    @static_fee.setter
    def static_fee(self, static_fee):
        """Sets the static_fee of this AbstractPaymentMethod.

        The static fee for this payment method in euros  # noqa: E501

        :param static_fee: The static_fee of this AbstractPaymentMethod.  # noqa: E501
        :type: float
        """

        self._static_fee = static_fee

    @entity_property
    def dynamic_fee(self):
        """Gets the dynamic_fee of this AbstractPaymentMethod.  # noqa: E501

        The dynamic fee for this payment method as a percentage  # noqa: E501

        :return: The dynamic_fee of this AbstractPaymentMethod.  # noqa: E501
        :rtype: float
        """
        return self._dynamic_fee

    @dynamic_fee.setter
    def dynamic_fee(self, dynamic_fee):
        """Sets the dynamic_fee of this AbstractPaymentMethod.

        The dynamic fee for this payment method as a percentage  # noqa: E501

        :param dynamic_fee: The dynamic_fee of this AbstractPaymentMethod.  # noqa: E501
        :type: float
        """

        self._dynamic_fee = dynamic_fee

    @entity_property
    def name(self):
        """Gets the name of this AbstractPaymentMethod.  # noqa: E501

        The friendly name of this payment method  # noqa: E501

        :return: The name of this AbstractPaymentMethod.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AbstractPaymentMethod.

        The friendly name of this payment method  # noqa: E501

        :param name: The name of this AbstractPaymentMethod.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AbstractPaymentMethod, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AbstractPaymentMethod):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
