/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Adherent);
  }
}(this, function(expect, Adherent) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Adherent.PaymentMethodApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentMethodApi', function() {
    describe('paymentMethodGet', function() {
      it('should call paymentMethodGet successfully', function(done) {
        //uncomment below and update the code to test paymentMethodGet
        //instance.paymentMethodGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentMethodPaymentMethodIdGet', function() {
      it('should call paymentMethodPaymentMethodIdGet successfully', function(done) {
        //uncomment below and update the code to test paymentMethodPaymentMethodIdGet
        //instance.paymentMethodPaymentMethodIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentMethodPaymentMethodIdPatch', function() {
      it('should call paymentMethodPaymentMethodIdPatch successfully', function(done) {
        //uncomment below and update the code to test paymentMethodPaymentMethodIdPatch
        //instance.paymentMethodPaymentMethodIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentMethodPost', function() {
      it('should call paymentMethodPost successfully', function(done) {
        //uncomment below and update the code to test paymentMethodPost
        //instance.paymentMethodPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
