/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Adherent);
  }
}(this, function(expect, Adherent) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Adherent.PortApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PortApi', function() {
    describe('mabGet', function() {
      it('should call mabGet successfully', function(done) {
        //uncomment below and update the code to test mabGet
        //instance.mabGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('portGet', function() {
      it('should call portGet successfully', function(done) {
        //uncomment below and update the code to test portGet
        //instance.portGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('portPortIdDelete', function() {
      it('should call portPortIdDelete successfully', function(done) {
        //uncomment below and update the code to test portPortIdDelete
        //instance.portPortIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('portPortIdGet', function() {
      it('should call portPortIdGet successfully', function(done) {
        //uncomment below and update the code to test portPortIdGet
        //instance.portPortIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('portPortIdMabPut', function() {
      it('should call portPortIdMabPut successfully', function(done) {
        //uncomment below and update the code to test portPortIdMabPut
        //instance.portPortIdMabPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('portPortIdPut', function() {
      it('should call portPortIdPut successfully', function(done) {
        //uncomment below and update the code to test portPortIdPut
        //instance.portPortIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('portPortIdStatePut', function() {
      it('should call portPortIdStatePut successfully', function(done) {
        //uncomment below and update the code to test portPortIdStatePut
        //instance.portPortIdStatePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('portPortIdVlanPut', function() {
      it('should call portPortIdVlanPut successfully', function(done) {
        //uncomment below and update the code to test portPortIdVlanPut
        //instance.portPortIdVlanPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('portPost', function() {
      it('should call portPost successfully', function(done) {
        //uncomment below and update the code to test portPost
        //instance.portPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('stateGet', function() {
      it('should call stateGet successfully', function(done) {
        //uncomment below and update the code to test stateGet
        //instance.stateGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('vlanGet', function() {
      it('should call vlanGet successfully', function(done) {
        //uncomment below and update the code to test vlanGet
        //instance.vlanGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
