###############################################################################
# 1st stage, launch the app
###############################################################################
FROM node:18-alpine@sha256:f4d6916c5625853e81994b5cb53ad3eb27e5fec9451c579d298fee0c508fe621
WORKDIR /adh6/frontend_angular

COPY package.json .
RUN yarn install --frozen-lockfile

COPY . .
ENV NODE_OPTIONS=--openssl-legacy-provider

CMD ["yarn", "start:en", "--watch", "--host", "0.0.0.0", "--disable-host-check"]

