TESTING_CLIENT_TOKEN = "TEST_TOKEN"
SAMPLE_CLIENT_TOKEN = "TEST_TOKEN_SAMPLE"
TESTING_CLIENT = "TestingClient"
TESTING_CLIENT_ID = 28
SAMPLE_CLIENT = "SampleMember"
SAMPLE_CLIENT_ID = 31

OIDC_TESTING_USERNAME = "adh6_testing"
OIDC_TESTING_PASSWORD = "adh6_testing_password"
