/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Port from '../model/Port';

/**
* Port service.
* @module api/PortApi
* @version 1.0.0
*/
export default class PortApi {

    /**
    * Constructs a new PortApi. 
    * @alias module:api/PortApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Check whether MAB is enable on this port or not.
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    mabGetWithHttpInfo(portId) {
      let postBody = null;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling mabGet");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/port/{port_id}/mab/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Check whether MAB is enable on this port or not.
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    mabGet(portId) {
      return this.mabGetWithHttpInfo(portId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Filter ports
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit the number of ports returned in the result. Default is 100 (default to 100)
     * @param {Number} opts.offset Skip the first n results (default to 0)
     * @param {Number} opts.switchID Filter only ports from that switch
     * @param {Number} opts.roomNumber Filter only ports from that room
     * @param {String} opts.terms Search terms
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Port>} and HTTP response
     */
    portGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'switchID': opts['switchID'],
        'roomNumber': opts['roomNumber'],
        'terms': opts['terms']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Port];
      return this.apiClient.callApi(
        '/port/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Filter ports
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit the number of ports returned in the result. Default is 100 (default to 100)
     * @param {Number} opts.offset Skip the first n results (default to 0)
     * @param {Number} opts.switchID Filter only ports from that switch
     * @param {Number} opts.roomNumber Filter only ports from that room
     * @param {String} opts.terms Search terms
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Port>}
     */
    portGet(opts) {
      return this.portGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a port
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    portPortIdDeleteWithHttpInfo(portId) {
      let postBody = null;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling portPortIdDelete");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/port/{port_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a port
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    portPortIdDelete(portId) {
      return this.portPortIdDeleteWithHttpInfo(portId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieve a port
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Port} and HTTP response
     */
    portPortIdGetWithHttpInfo(portId) {
      let postBody = null;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling portPortIdGet");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Port;
      return this.apiClient.callApi(
        '/port/{port_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieve a port
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Port}
     */
    portPortIdGet(portId) {
      return this.portPortIdGetWithHttpInfo(portId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Enable/disable MAB on a port
     * @param {Number} portId 
     * @param {Boolean} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    portPortIdMabPutWithHttpInfo(portId, body) {
      let postBody = body;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling portPortIdMabPut");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling portPortIdMabPut");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/port/{port_id}/mab/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Enable/disable MAB on a port
     * @param {Number} portId 
     * @param {Boolean} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    portPortIdMabPut(portId, body) {
      return this.portPortIdMabPutWithHttpInfo(portId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a port
     * @param {Number} portId 
     * @param {module:model/Port} port Port to update
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    portPortIdPutWithHttpInfo(portId, port) {
      let postBody = port;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling portPortIdPut");
      }
      // verify the required parameter 'port' is set
      if (port === undefined || port === null) {
        throw new Error("Missing the required parameter 'port' when calling portPortIdPut");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/port/{port_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update a port
     * @param {Number} portId 
     * @param {module:model/Port} port Port to update
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    portPortIdPut(portId, port) {
      return this.portPortIdPutWithHttpInfo(portId, port)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Shutdown/enable a port
     * @param {Number} portId 
     * @param {Boolean} body True to open, False to shutdown
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    portPortIdStatePutWithHttpInfo(portId, body) {
      let postBody = body;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling portPortIdStatePut");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling portPortIdStatePut");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/port/{port_id}/state/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Shutdown/enable a port
     * @param {Number} portId 
     * @param {Boolean} body True to open, False to shutdown
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    portPortIdStatePut(portId, body) {
      return this.portPortIdStatePutWithHttpInfo(portId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Change the VLAN assigned a to port
     * @param {Number} portId 
     * @param {Number} body VLAN to assign. Set it to 1 if you want to enable authentication on the port.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    portPortIdVlanPutWithHttpInfo(portId, body) {
      let postBody = body;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling portPortIdVlanPut");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling portPortIdVlanPut");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/port/{port_id}/vlan/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Change the VLAN assigned a to port
     * @param {Number} portId 
     * @param {Number} body VLAN to assign. Set it to 1 if you want to enable authentication on the port.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    portPortIdVlanPut(portId, body) {
      return this.portPortIdVlanPutWithHttpInfo(portId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a port
     * @param {module:model/Port} port Port to create
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    portPostWithHttpInfo(port) {
      let postBody = port;
      // verify the required parameter 'port' is set
      if (port === undefined || port === null) {
        throw new Error("Missing the required parameter 'port' when calling portPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/port/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a port
     * @param {module:model/Port} port Port to create
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    portPost(port) {
      return this.portPostWithHttpInfo(port)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieve the status of a port.
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Boolean} and HTTP response
     */
    stateGetWithHttpInfo(portId) {
      let postBody = null;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling stateGet");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Boolean';
      return this.apiClient.callApi(
        '/port/{port_id}/state/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieve the status of a port.
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Boolean}
     */
    stateGet(portId) {
      return this.stateGetWithHttpInfo(portId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieve the VLAN assigned to the port.
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Number} and HTTP response
     */
    vlanGetWithHttpInfo(portId) {
      let postBody = null;
      // verify the required parameter 'portId' is set
      if (portId === undefined || portId === null) {
        throw new Error("Missing the required parameter 'portId' when calling vlanGet");
      }

      let pathParams = {
        'port_id': portId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Number';
      return this.apiClient.callApi(
        '/port/{port_id}/vlan/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieve the VLAN assigned to the port.
     * @param {Number} portId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Number}
     */
    vlanGet(portId) {
      return this.vlanGetWithHttpInfo(portId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
