/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ModelSwitch from '../model/ModelSwitch';

/**
* Switch service.
* @module api/SwitchApi
* @version 1.0.0
*/
export default class SwitchApi {

    /**
    * Constructs a new SwitchApi. 
    * @alias module:api/SwitchApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get all switches
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit the number of switches returned in the result. Default is 100 (default to 100)
     * @param {Number} opts.offset Skip the first n results (default to 0)
     * @param {String} opts.terms Search terms
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ModelSwitch>} and HTTP response
     */
    switchGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'terms': opts['terms']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ModelSwitch];
      return this.apiClient.callApi(
        '/switch/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get all switches
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Limit the number of switches returned in the result. Default is 100 (default to 100)
     * @param {Number} opts.offset Skip the first n results (default to 0)
     * @param {String} opts.terms Search terms
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ModelSwitch>}
     */
    switchGet(opts) {
      return this.switchGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a switch
     * @param {module:model/ModelSwitch} modelSwitch Switch to create
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    switchPostWithHttpInfo(modelSwitch) {
      let postBody = modelSwitch;
      // verify the required parameter 'modelSwitch' is set
      if (modelSwitch === undefined || modelSwitch === null) {
        throw new Error("Missing the required parameter 'modelSwitch' when calling switchPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/switch/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create a switch
     * @param {module:model/ModelSwitch} modelSwitch Switch to create
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    switchPost(modelSwitch) {
      return this.switchPostWithHttpInfo(modelSwitch)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete a switch
     * @param {Number} switchID 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    switchSwitchIDDeleteWithHttpInfo(switchID) {
      let postBody = null;
      // verify the required parameter 'switchID' is set
      if (switchID === undefined || switchID === null) {
        throw new Error("Missing the required parameter 'switchID' when calling switchSwitchIDDelete");
      }

      let pathParams = {
        'switchID': switchID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/switch/{switchID}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete a switch
     * @param {Number} switchID 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    switchSwitchIDDelete(switchID) {
      return this.switchSwitchIDDeleteWithHttpInfo(switchID)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieve a switch
     * @param {Number} switchID 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ModelSwitch} and HTTP response
     */
    switchSwitchIDGetWithHttpInfo(switchID) {
      let postBody = null;
      // verify the required parameter 'switchID' is set
      if (switchID === undefined || switchID === null) {
        throw new Error("Missing the required parameter 'switchID' when calling switchSwitchIDGet");
      }

      let pathParams = {
        'switchID': switchID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelSwitch;
      return this.apiClient.callApi(
        '/switch/{switchID}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieve a switch
     * @param {Number} switchID 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ModelSwitch}
     */
    switchSwitchIDGet(switchID) {
      return this.switchSwitchIDGetWithHttpInfo(switchID)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update a switch
     * @param {Number} switchID 
     * @param {module:model/ModelSwitch} modelSwitch Switch to update
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    switchSwitchIDPutWithHttpInfo(switchID, modelSwitch) {
      let postBody = modelSwitch;
      // verify the required parameter 'switchID' is set
      if (switchID === undefined || switchID === null) {
        throw new Error("Missing the required parameter 'switchID' when calling switchSwitchIDPut");
      }
      // verify the required parameter 'modelSwitch' is set
      if (modelSwitch === undefined || modelSwitch === null) {
        throw new Error("Missing the required parameter 'modelSwitch' when calling switchSwitchIDPut");
      }

      let pathParams = {
        'switchID': switchID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/switch/{switchID}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update a switch
     * @param {Number} switchID 
     * @param {module:model/ModelSwitch} modelSwitch Switch to update
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    switchSwitchIDPut(switchID, modelSwitch) {
      return this.switchSwitchIDPutWithHttpInfo(switchID, modelSwitch)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
