/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountTypePatchRequest model module.
 * @module model/AccountTypePatchRequest
 * @version 1.0.0
 */
class AccountTypePatchRequest {
    /**
     * Constructs a new <code>AccountTypePatchRequest</code>.
     * @alias module:model/AccountTypePatchRequest
     */
    constructor() { 
        
        AccountTypePatchRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountTypePatchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountTypePatchRequest} obj Optional instance to populate.
     * @return {module:model/AccountTypePatchRequest} The populated <code>AccountTypePatchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountTypePatchRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
AccountTypePatchRequest.prototype['name'] = undefined;






export default AccountTypePatchRequest;

