/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Room model module.
 * @module model/Room
 * @version 1.0.0
 */
class Room {
    /**
     * Constructs a new <code>Room</code>.
     * @alias module:model/Room
     * @param roomNumber {Number} 
     */
    constructor(roomNumber) { 
        
        Room.initialize(this, roomNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, roomNumber) { 
        obj['roomNumber'] = roomNumber;
    }

    /**
     * Constructs a <code>Room</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Room} obj Optional instance to populate.
     * @return {module:model/Room} The populated <code>Room</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Room();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'Number');
            }
            if (data.hasOwnProperty('roomNumber')) {
                obj['roomNumber'] = ApiClient.convertToType(data['roomNumber'], 'Number');
            }
            if (data.hasOwnProperty('vlan')) {
                obj['vlan'] = ApiClient.convertToType(data['vlan'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
Room.prototype['description'] = undefined;

/**
 * @member {Number} phone
 */
Room.prototype['phone'] = undefined;

/**
 * @member {Number} roomNumber
 */
Room.prototype['roomNumber'] = undefined;

/**
 * @member {Number} vlan
 */
Room.prototype['vlan'] = undefined;






export default Room;

