/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Transaction model module.
 * @module model/Transaction
 * @version 1.0.0
 */
class Transaction {
    /**
     * Constructs a new <code>Transaction</code>.
     * @alias module:model/Transaction
     * @param dst {Number} 
     * @param name {String} 
     * @param src {Number} 
     * @param type {Number} 
     * @param value {Number} 
     */
    constructor(dst, name, src, type, value) { 
        
        Transaction.initialize(this, dst, name, src, type, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dst, name, src, type, value) { 
        obj['dst'] = dst;
        obj['name'] = name;
        obj['src'] = src;
        obj['type'] = type;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>Transaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Transaction} obj Optional instance to populate.
     * @return {module:model/Transaction} The populated <code>Transaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Transaction();

            if (data.hasOwnProperty('attachements')) {
                obj['attachements'] = ApiClient.convertToType(data['attachements'], 'String');
            }
            if (data.hasOwnProperty('dst')) {
                obj['dst'] = ApiClient.convertToType(data['dst'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ApiClient.convertToType(data['product'], 'Number');
            }
            if (data.hasOwnProperty('src')) {
                obj['src'] = ApiClient.convertToType(data['src'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} attachements
 */
Transaction.prototype['attachements'] = undefined;

/**
 * @member {Number} dst
 */
Transaction.prototype['dst'] = undefined;

/**
 * @member {Number} id
 */
Transaction.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Transaction.prototype['name'] = undefined;

/**
 * @member {Number} product
 */
Transaction.prototype['product'] = undefined;

/**
 * @member {Number} src
 */
Transaction.prototype['src'] = undefined;

/**
 * @member {Number} timestamp
 */
Transaction.prototype['timestamp'] = undefined;

/**
 * @member {Number} type
 */
Transaction.prototype['type'] = undefined;

/**
 * @member {Number} value
 */
Transaction.prototype['value'] = undefined;






export default Transaction;

