"""empty message

Revision ID: 81c7f88145f4
Revises: 83909d12e1cd
Create Date: 2021-04-13 13:13:45.739838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81c7f88145f4'
down_revision = '83909d12e1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adherents_ibfk_2', 'adherents', type_='foreignkey')
    op.drop_column('adherents', 'admin_id')
    op.drop_table('admins')
    op.add_column('adherents', sa.Column('roles', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adherents', sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('adherents_ibfk_2', 'adherents', 'admins', ['admin_id'], ['id'])
    op.drop_column('adherents', 'roles')
    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('roles', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
