"""empty message

Revision ID: 83909d12e1cd
Revises: 8193644a753f
Create Date: 2021-03-27 16:00:11.554003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83909d12e1cd'
down_revision = '8193644a753f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vlans', sa.Column('excluded_addr', sa.String(length=255), nullable=True))
    op.add_column('vlans', sa.Column('excluded_addrv6', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vlans', 'excluded_addrv6')
    op.drop_column('vlans', 'excluded_addr')
    # ### end Alembic commands ###
